web:
    image: nginx:latest
    ports:
        - "127.0.0.1:8080:80"
    volumes:
        - ./app:/usr/src/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
app:
    build: .
    volumes:
        - ./app:/usr/src/app
    links:
        - mysql
mysql:
    image: mysql:latest
    volumes:
        - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
